#!/bin/sh

base_dir=$( cd $(dirname $0) && pwd )
source $base_dir/common.sh

if [ $# -lt 2 ]; then
  echo "usage: $0 <target_dir> package {package ...}"
  exit 21
fi

root="$(cd $1 && pwd)"

target="$root"
build="$root/build"
shift;

mkdir -p "$target" "$build"

for p in $@; do
  target="$root/$p"
  if [ -d "$target" ] ; then
    [ $skip = "y" ] && {
      echo "skipping $p"
      continue
    }
    [ $delete = "y" ] && rm -r "$target" ||
    error "directory for $p already exists"
  fi
  run_scripts download_unpack pre_build build_install
done
