#!/bin/bash

base_dir=$( cd $(dirname $0) && pwd )
source $base_dir/common.sh

if [ $# -lt 2 ]; then
  echo "usage: $0 <target_dir> [-s <source_dir>] package {package ...}"
  exit 21
fi

root="$(mkdir -p $1 && cd $1 && pwd)"

target="$root"
build="${BUILD_DIR:-$root/build}"
shift;

case $1 in
  --source|-s)  SOURCE="$2"; shift; shift;;
esac

mkdir -p "$target"
mkdir -p "$build"

packages=$( with_deps $@ )
build="${SOURCE:-${build}}"

for p in $packages; do
  target="$root/$p"
  export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:$target"
  if [ -d "$target" ] ; then
    if [ $duplicate = "skip" ]; then
      message "skipping $p" &&
      continue
    elif [ $duplicate = "remove" ]; then
      message "removing existing package $p" &&
      rm -r "$target"
    elif  [ $duplicate = "rebuild" ]; then
        message "rebuilding existing package $p" &&
  	run_scripts build_install
	continue
    else
      error "directory for $p already exists"
    fi
  fi
  run_scripts download_unpack pre_build build_install
done
